version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: "dev"
      NEXT_PUBLIC_ENV: "development"
      NEXT_PUBLIC_TELEGRAM_BOT_TOKEN_DEV: ""
      NEXT_PUBLIC_TELEGRAM_BOT_TOKEN: ""
      CAPSULE_API_KEY: ""
      CAPSULE_ENV: "BETA"
      VITE_SERVER_URL: ""
      KV_REST_API_TOKEN: ""
      KV_REST_API_URL: ""
    volumes:
      - .:/src
    command: ["npm", "run", "start"]
